name: "Mark and close stale issues"
on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment on this issue, or it will be closed in 60 days.'
        days-before-stale: 90
        days-before-close: 60
        close-issue-message: 'Issue closed due to inactivity.'
        stale-issue-label: 'status/stale'
        stale-pr-label: 'status/stale'
        exempt-issue-labels: 'triage/accepted,triage/discuss,kind/design-issue,kind/health,kind/roadmap-item,kind/task'
