name: "Label and close stale issues & PRs"

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/stale@v9
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 90
        days-before-close: 60
        stale-issue-label: 'status/stale'
        stale-pr-label: 'status/stale'
        exempt-issue-labels: 'triage/accepted,triage/discuss,kind/design-issue,kind/health,kind/roadmap-item,kind/task'
        stale-issue-message: >
          This issue has been automatically labeled as stale because 90 days
          have passed without comments or other activity. If no further
          activity occurs and the `status/stale` label is not removed within
          60 days, it will be closed. If you believe this is in error or would
          like to discuss it further, please leave a comment here.
        stale-pr-message: >
          This pull request has been automatically labeled as stale because 90
          days have passed without comments or other activity. If no further
          activity occurs and the `status/stale` label is not removed within 60
          days, it will be closed. If you believe this is in error or would
          like to discuss it further, please leave a comment here.
        close-issue-message: >
          This issue has been closed due to inactivity for 60 days since the
          time the stale label was applied. If you believe this is in error or
          would like to discuss it further, please either open a new issue
          (and reference this one in it, for continuity) or reach out to the
          Cirq project maintainers at quantum-oss-maintainers@google.com.
        close-pr-message: >
          This pull-request has been closed due to inactivity for 60 days
          since the time the stale label was applied. If you believe this is
          in error or would like to discuss it further, please reach out to
          the Cirq project maintainers at quantum-oss-maintainers@google.com.
